### ISSUE TITLE
I want to upload pics from computer

### ISSUE THREAD

**Issue by yopaseopor** [openstreetview/openstreetview.org#9] opened 2016-07-25 10:19 UTC
Hi. 
I like open source, and also like street view projects. I have some street view pics (160ks) so I want to upload via web (via app I have tried...and I have failed). Will be this possible?

**Comment by james2432** [comment] 2016-07-26 01:54
in beta they had python scripts to upload such files, and they were working on a GUI application. I'm sure they will make it available soon.

**Comment by bogdans-telenav** [comment] 2016-07-26 05:55
@yopaseopor as @james2432 said we have some scripts for doing exactly this also we are working on a GUI and they will be public in a few days.
@james2432 thanks for your answers.

**Comment by martijnv-telenav** [comment] 2016-07-26 20:36
duplicate of #7

**Closed by martijnv-telenav** 2016-07-26 20:36 UTC
