### ISSUE TITLE
I want to download the .apk file

### ISSUE THREAD

**Issue by de-vries** [openstreetview/openstreetview.org#39] opened 2016-08-06 19:35 UTC
But I can't find it on the site. 
I'd like to try openstreetview, but I'm not letting google services into my phone to get the app. Please conciser offering a direct download and/or put the app in F-Droid.

**Comment by james2432** [comment] 2016-08-06 23:26
Should be under android branch, also duplicate of #8 under android branch

**Comment by martijnv-telenav** [comment] 2016-08-10 22:41
I think it's better reported here as it would be a web site (openstreetview.org) download. So I'll close the Android one and leave this open.

**Comment by martijnv-telenav** [comment] 2016-08-21 18:38
The APK is here: https://www.dropbox.com/s/8gmjj63sl6fqjoe/app-release-1.9.5.apk?dl=0

**Closed** 2016-08-21 18:39 UTC

**Comment by dex2000** [comment] 2016-08-22 22:30
apk should be downloadable directly on github AND from the website.

**Comment by tagawa** [comment] 2016-08-23 03:13
Yes, please could you add a direct link to the APK from the "Get the app" button on the website?

**Comment by Zahnstocher** [comment] 2016-08-24 09:34
@martijnv-telenav 

> The APK is here: https://www.dropbox.com/s/8gmjj63sl6fqjoe/app-release-1.9.5.apk?dl=0

I installed this APK, but I can't use it.
If I try to start it, a pop-up appears:

> OSV won't run unless you update Google Play services.
> Update

If I click on "Update", nothing happens, because I don't have Google Play on my device.

I think it does not make much sense to provide a direct download APK, to bypass Google Play, if I actually need it to run.

Please provide a APK without Google Play dependency.
Thank you!

**Comment by james2432** [comment] 2016-08-24 10:23
This is probably because they require the gps to be aquired through play services instead of directly

**Comment by mvexel** [comment] 2016-09-23 16:23
Can we put this as a link to the latest version on the web site?

**Comment by mvexel** [comment] 2016-09-23 16:24
@james2432 not necessarily - for example Mapzen has a drop in replacement for google location services IIRC.

**Comment by james2432** [comment] 2016-09-23 16:51
@mvexel On android (without 3rd party libraries) can request the GPS location from either: 
Google Play Services(must have google play intalled)(which might cache gps location for faster requests/aquisition) 

**or** 

directly from the device (slower because it actually has to locate itself and not from cache) and it can also be from gps onboard or the cell network(less accurate)


If you use Google Play Services for acquiring the GPS you create a dependency to google play to be installed on the android system. If you acquire directly the dependency is no longer there(this includes libraries that aquires GPS location for you as they are using the APIs to access the direct GPS).
