### ISSUE TITLE
Login to http://openstreetview.org/

### ISSUE THREAD

**Issue by iagsav** [openstreetview/openstreetview.org#34] opened 2016-08-03 14:35 UTC
Every time I go to a website I have to enter their credentials to log in to your profile. The accounting data is reset when you close the browser

**Comment by ToeBee** [comment] 2016-08-03 16:51
Is this a duplicate of #13?

**Comment by iagsav** [comment] 2016-08-03 17:51
Hello! i think it is similar but not the same

**Comment by james2432** [comment] 2016-08-04 05:22
it's a duplicate, the reason you have to log in every time is because the oauth token is dropped

**Comment by alexandrui-telenav** [comment] 2016-08-05 14:50
hi @ToeBee , appreciate you reported this. It's something we'll tackle in the current sprint so hopefully by the end of next week will be fixed.

**Comment by martijnv-telenav** [comment] 2016-08-10 22:37
Closing as duplicate of #13

**Closed** 2016-08-10 22:38 UTC
