### ISSUE TITLE
Reflection horizontal images

### ISSUE THREAD

**Issue by moscowpan** [openstreetview/openstreetview.org#70] opened 2016-08-26 08:52 UTC
In track http://openstreetview.org/details/14857/1 all images are reflection horizontal, like in a mirror and it seems like in Russia (Moscow) left side traffic. I used Android app and Samsung Note 4. Can you check it and display images correctly?

**Comment by reinvented** [comment] 2016-08-26 14:07
I suspect this is a duplicate of [this issue for the Android app](https://github.com/openstreetview/android/issues/3), also [noted here](https://github.com/openstreetview/android/issues/36).

**Comment by kalmanbencze** [comment] 2016-08-29 11:28
this issue is fixed in version 1.9.6

**Closed by kalmanbencze** 2016-08-29 11:28 UTC

**Comment by moscowpan** [comment] 2016-08-30 10:15
@reinvented @kalmanbencze  Would you mirror images in that track again or I have to delete this thack?

**Comment by kalmanbencze** [comment] 2016-08-30 10:34
As of now we can only post-rotate incorrectly rotated images, I will have to discuss with the backend developer if we can add this functionality, but it will take time most probably.
How much data are we talking about, how many of your pictures?

**Comment by kalmanbencze** [comment] 2016-08-30 10:37
is this the only track that you have with mirrored images?

**Comment by moscowpan** [comment] 2016-08-30 10:37
We are talking only about that track, 605 images.

**Comment by kalmanbencze** [comment] 2016-08-30 10:38
you can leave the track for now, I'll discuss with the backend dev, and come back with a response.
Have you experiences the issue with version 1.9.6 or 1.9.7?

**Comment by kalmanbencze** [comment] 2016-08-30 10:43
So I've talked with the dev, it can be done but only later on. So keep the track, and I'll notify you when the images get corrected.

**Comment by moscowpan** [comment] 2016-08-30 10:45
Thank you, I will keep it.
I have updated to 1.9.7 but not try to use it yet. I will write about experiance later.
